# Generated by Django 4.0.6 on 2023-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('species', models.CharField(max_length=100)),
                ('tree_height', models.FloatField()),
                ('steam_diameter', models.FloatField()),
                ('crown_height', models.FloatField()),
                ('crown_diameter', models.FloatField()),
                ('spreading', models.CharField(max_length=50)),
                ('crown_damage', models.CharField(max_length=50)),
                ('reason_crown_damage', models.CharField(max_length=1000)),
                ('trunk_damage', models.CharField(max_length=50)),
                ('reason_trunk_damage', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
