# Generated by Django 4.0.6 on 2024-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree_Tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='survey',
            name='crown_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='trunk_damage',
            field=models.FloatField(),
        ),
    ]
